baseURL = 'https://suttergustavo.github.io/'
languageCode = 'en-us'
title = 'Gustavo Sutter'
theme = 'minimal'



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [["\\[", "\\]"], ["$$", "$$"]]
          inline = [["\\(", "\\)"], ["$", "$"]]
  [markup.highlight]
    style = "github"
    lineNos = false
    codeFences = true
    guessSyntax = true
    noClasses = false

[params]
  favicon = "👨‍💻"
  author = "Gustavo Sutter"
  description = "Academic website and blog"
  role = "PhD Student"
  affiliation = "University of Waterloo"
  photo = "/images/profile.png"
  email = "gsutterp [at] uwaterloo [dot] ca"
  scholar = "https://scholar.google.com/citations?user=r6Jwv5UAAAAJ"
  # github = "https://github.com/yourusername"
  bluesky = "https://bsky.app/profile/suttergustavo.bsky.social"

  disablePublications = true
  
